services:
  - type: web
    name: knowledge-base-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:3000,https://knowledge-base-app-2k5o.vercel.app
      - key: TOP_K_RESULTS
        value: 3
      - key: MIN_RELEVANCE_SCORE
        value: 50.0
